project:
  type: website

website:
  description: "逃之夭夭's Blog"
  site-url: https://github.com/TheSecondStep/Quarto-Blog # you must change this appropriately for RSS feeds to work properly
  title: "逃之夭夭 Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/TheSecondStep
  comments:
    giscus:
      repo: TheSecondStep/Quarto-Blog
      repo-id: R_kgDORAnNLQ
      category: General
      category-id: DIC_kwDORAnNLc4C1bgz
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: light
      language: zh-CN
      loading: lazy
format:
  html:
    code-copy: true
    code-border: true
    theme:
      - flatly
      - brand
    css: styles.css
    



